aplayer:
  global: true
  meting: false
  # https://github.com/metowolf/MetingJS/tree/v1.2#option
  widget:
    enable: true
    autoplay: false
    # theme: "#2980b9"
    loop: all
    order: list
    preload: auto
    volume: 0.7
    mutex: true
    lrcType: 0
    listFolded: true
    listMaxHeight: 340px
    audio:
#      - name: PICO PARK
#        artist: TECOPARK
#        url: https://cdn.jsdelivr.net/gh/Big-Cake-jpg/Music-CakeMC/PICO%20PARK.mp3
#        cover: https://s2.loli.net/2022/06/12/xc9iU3YWKnwFqJ1.jpg
      - name: Eternal Anamnesis æ°¸æ’çš„å›å¿†
        artist: é™ˆè‡´é€¸ / HOYO-MiX
        url: https://resources.cakeskin.tk/file/bigcake-blog-resources/musics/Eternal-Anamnesis.mp3
        cover: https://p2.music.126.net/odoWDzYyHAe-IzLzRxkg3Q==/109951165336802038.jpg
      - name: Remembrance ä¸€æ®µå›å¿†
        artist: é™ˆè‡´é€¸ / HOYO-MiX
        url: https://resources.cakeskin.tk/file/bigcake-blog-resources/musics/Remembrance.flac
        cover: https://p2.music.126.net/odoWDzYyHAe-IzLzRxkg3Q==/109951165336802038.jpg
      - name: Moonlight in Mondstadt è’™å¾·çš„æœˆå…‰
        artist: é™ˆè‡´é€¸ / HOYO-MiX
        url: https://resources.cakeskin.tk/file/bigcake-blog-resources/musics/Moonlight-in-Mondstadt.flac
        cover: https://p2.music.126.net/odoWDzYyHAe-IzLzRxkg3Q==/109951165336802038.jpg
      - name: Mondstadt Starlit æ˜Ÿå…‰ä¸‹çš„è’™å¾·
        artist: é™ˆè‡´é€¸ / HOYO-MiX
        url: https://resources.cakeskin.tk/file/bigcake-blog-resources/musics/Mondstadt-Starlit.flac
        cover: https://p2.music.126.net/odoWDzYyHAe-IzLzRxkg3Q==/109951165336802038.jpg
      - name: otherside
        artist: Lena Raine
        url: https://resources.cakeskin.tk/file/bigcake-blog-resources/musics/otherside.mp3
        cover: https://p2.music.126.net/ly16g4KsYaOCe6cj09SQMw==/109951166959790351.jpg
      - name: ãµã‚ãµã‚â™ª
        artist: ç‰§é‡ç”±ä¾
        url: https://resources.cakeskin.tk/file/bigcake-blog-resources/musics/ãµã‚ãµã‚â™ª.mp3
        cover: https://s2.loli.net/2022/06/12/bpgOT9Hr3sWcGv5.jpg
      - name: å›ã ã£ãŸã‚‰
        artist: HAPPY BIRTHDAY
        url: https://resources.cakeskin.tk/file/bigcake-blog-resources/musics/å›ã ã£ãŸã‚‰.mp3
        cover: https://s2.loli.net/2022/06/12/eQX8Y9rHbmjxstu.jpg
      - name: å¯æ„›ããªã‚ŠãŸã„
        artist: é–é‚£
        url: https://resources.cakeskin.tk/file/bigcake-blog-resources/musics/å¯æ„›ããªã‚ŠãŸã„.mp3
        cover: https://s2.loli.net/2022/06/12/yak6vnq9GQAViRB.jpg
    meting:
      enable: false
      id: 308168565
      server: netease
      type: playlist

say:
  enable: true
  # api: https://say.elpsy.cn/sentences.json
  # /data/sentences.json
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # src is the script
  src: /js/say.js
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn
    # api: https://v1.hitokoto.cn?c=a&c=b&c=c&c=d&c=k

reward:
  enable: true
  icon: fluent:document-heart-20-regular
  comment: éƒ½çœ‹äº†è¿™ä¹ˆå¤šæ–‡ç« äº†ï¼Œä¸è€ƒè™‘æ‰“ç‚¹é’±å—ï¼ˆ
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: æ”¯ä»˜å®
      path: https://resources.cakeskin.tk/file/bigcake-blog-resources/images/alipay-qrcode.png
      color: "#00A3EE"
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      path: https://resources.cakeskin.tk/file/bigcake-blog-resources/images/qq-qrcode.png
      color: "#12B7F5"
      icon: ri:qq-line
  
bg_image:
  enable: true
  url: https://resources.cakeskin.tk/file/bigcake-blog-resources/images/bg-bright-blur-30px.png # recomend image related to your mode
  dark: https://resources.cakeskin.tk/file/bigcake-blog-resources/images/bg-dark-blur-30px.png

cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

banner:
  enable: true
  title: å¤§è›‹ç³•çš„çƒ˜ç„™åŠ
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: fluent:chevron-down-16-regular

pjax:
  enable: true
  src: /js/pjax.js

avatar:
  enable: true
  url: https://resources.cakeskin.tk/file/bigcake-blog-resources/images/avatar.jpg
  # If true, the avatar would be dispalyed in circle.
  rounded: true
  # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ› ï¸
    message: Playing Minecraft.

pages:
  - name: å‹é“¾
    url: /links/
    icon: fluent:people-12-regular
    color: dodgerblue

social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: fluent:rss-20-regular
    color: orange
  - name: QQ
    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
    link: http://wpa.qq.com/msgrd?v=3&uin=2577117205&site=qq&menu=yes
    icon: ri:qq-line
    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/Big-Cake-jpg
    icon: ri:github-line
    color: "#6e5494"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=3812611237
    icon: ri:netease-cloud-music-line
    color: "#C20C0C"
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/bigcake-19
    icon: ri:zhihu-line
    color: "#0084FF"
  - name: Twitter
    link: https://twitter.com/BigCake080105
    icon: ri:twitter-line
    color: "#1da1f2"
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/523235567
    icon: ri:bilibili-line
    color: "#FF8EB3"
  # - name: POPI
  #   link: https://www.popiapp.cn/elpsycn
  #   icon: ri:questionnaire-line
  #   color: "#525252"
  - name: Telegram
    link: https://t.me/BigCakeBlog
    icon: ri:telegram-line
    color: "#0088CC"
  - name: ç™¾åº¦è´´å§
    link: https://tieba.baidu.com/home/main?id=tb.1.f0f48c80.0RMWKRqi00nEW65GQhsxQA?t=1586957539&fr=index
    icon: ri:baidu-line
    color: "#317ef3"
  - name: E-Mail
    link: mailto:bigcake@cakemc.top
    icon: fluent:mail-16-regular
    color: "#8E71C1"

favicon: https://resources.cakeskin.tk/file/bigcake-blog-resources/images/avatar.jpg

baidu_push: true

feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

mourn:
  enable: true
  days:
    - "4-4"
    - "9-18"
    - "12-13"

local_search:
  enable: false
  src: /js/search/local-search.js

menu:
  home:
    path: /
    icon: fluent:home-24-regular
  list:
    - type: archives
      path: /archives/
      icon: fluent:archive-24-regular
    - type: categories
      path: /categories/
      icon: fluent:folder-24-regular
    - type: tags
      path: /tags/
      icon: fluent:tag-24-regular
  custom:
    title: å¼€å¾€
    path: https://travellings.link
    icon: fluent:vehicle-subway-24-regular

google_analytics:
  enable: true
  # GA4
  id: G-WXBXYV2R6B

footer:
  since: 2021

  # Icon between year and copyright info.
  icon:
    # `heart` is recommended with animation in red (#ff0000).
    name: fluent:heart-16-filled
    # If you want to animate the icon, set it to true.
    animated: true
    # Change the color of icon, using Hex Code.
    color: "#ff0000"
    # url: https://sponsors.yunyoujun.cn
    # title: äº‘æ¸¸å›çš„èµåŠ©è€…ä»¬
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2021-09-20T22:15:00"
  powered:
    # Hexo link (Powered by Hexo).
    enable: true
  support:
    enable: true
    title: åˆæ‹äº‘
    link: https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral
    logo: https://resources.cakeskin.tk/file/bigcake-blog-resources/images/upyun-logo.png
    prefix: æœ¬ç½‘ç«™ç”±
    suffix: æä¾› CDN åŠ é€Ÿä¸äº‘å­˜å‚¨æœåŠ¡
  custom_text: <a href="https://travellings.link" target="_blank"><img height="25" alt="travellings" src="https://travellings.link/assets/logo.svg"></a>

google_adsense:
  enable: true
  client: ca-pub-3406300839504314

comment:
  enable: true
  icon: fluent:chat-24-regular
  tips:
    - å¯ä»¥è¯´å‡ å¥è¯å˜›^_^å¦‚æœçœ‹ä¸åˆ°è¯„è®ºï¼Œè¯·åˆ·æ–°å‡ æ¬¡
  candidates:
    - waline
utterances:
  enable: false
  repo: Big-Cake-jpg/big-cake-jpg.github.io
  issue-term: title
  label: comment
  theme: github-light
waline:
  enable: true
  serverURL: https://waline.bigcake.cakemc.top
  comment: true
  emoji:
    - https://unpkg.onmicrosoft.cn/@waline/emojis@latest/bilibili/
    - https://unpkg.onmicrosoft.cn/@waline/emojis@latest/weibo/
    - https://unpkg.onmicrosoft.cn/@waline/emojis@latest/qq/
  locale:
    placeholder: æ±‚æ±‚ä½ äº†ï¼Œå†™ç‚¹è¯„è®ºå§ï¼ˆè¯·å…ˆç™»å½•ï¼‰
    
leancloud_visitors:
  enable: true
  app_id: ErznielzJTc0MWHWtbaznYKO-MdYXbMMI
  app_key: iK4BuSm3M35dNsuMerVlq3JO

wordcount:
  enable: true
  count: true
  time: true
  
colors:
  primary: "#F2BC57"
  bg: "#F2F2F2"
  
fireworks:
  enable: true
  colors:
    - "115, 75, 52"
    - "242, 188, 87"
    - "242, 205, 94"
    - "242, 242, 242"

algolia_search:
  enable: true

vendors:
  host: https://unpkg.onmicrosoft.cn/
  busuanzi: https://busuanzi.icodeq.com/busuanzi.pure.mini.js

medium_zoom: true

busuanzi:
  enable: true
  site_uv: true
  site_uv_icon: fluent:person-24-filled
  site_pv: true
  site_pv_icon: fluent:eye-24-filled
  page_pv: false
  page_pv_icon: fluent:document-person-16-regular

icons:
  # è¿”å›é¡¶éƒ¨
  back_to_top: fluent:arrow-up-24-regular
  # åˆ†ç±»
  category: fluent:folder-24-regular
  # æ ‡ç­¾
  tag: fluent:tag-24-regular
  # æ‹œè®¿
  view: fluent:document-person-16-regular
  wordcount: fluent:text-word-count-24-regular
  readtime: fluent:timer-24-regular
  
