aplayer:
  global: true
  meting: false
  # https://github.com/metowolf/MetingJS/tree/v1.2#option
  widget:
    enable: true
    autoplay: false
    # theme: "#2980b9"
    loop: all
    order: list
    preload: auto
    volume: 0.7
    mutex: true
    lrcType: 0
    listFolded: true
    listMaxHeight: 340px
    audio:
      - name: PICO PARK
        artist: TECOPARK
        url: https://cdn.jsdelivr.net/gh/Big-Cake-jpg/Music-CakeMC/PICO%20PARK.mp3
        cover: https://s2.loli.net/2022/06/12/xc9iU3YWKnwFqJ1.jpg
      - name: ãµã‚ãµã‚â™ª
        artist: ç‰§é‡ç”±ä¾
        url: https://cdn.jsdelivr.net/gh/Big-Cake-jpg/Music_For_My_Blog/ãµã‚ãµã‚â™ª.mp3
        cover: https://s2.loli.net/2022/06/12/bpgOT9Hr3sWcGv5.jpg
      - name: å›ã ã£ãŸã‚‰
        artist: HAPPY BIRTHDAY
        url: https://cdn.jsdelivr.net/gh/Big-Cake-jpg/Music_For_My_Blog/å›ã ã£ãŸã‚‰.mp3
        cover: https://s2.loli.net/2022/06/12/eQX8Y9rHbmjxstu.jpg
      - name: å¯æ„›ããªã‚ŠãŸã„
        artist: é–é‚£
        url: https://cdn.jsdelivr.net/gh/Big-Cake-jpg/Music_For_My_Blog/å¯æ„›ããªã‚ŠãŸã„.mp3
        cover: https://s2.loli.net/2022/06/12/yak6vnq9GQAViRB.jpg
    meting:
      enable: false
      id: 308168565
      server: netease
      type: playlist

say:
  enable: true
  # api: https://say.elpsy.cn/sentences.json
  # /data/sentences.json
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # src is the script
  src: /js/say.js
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn
    # api: https://v1.hitokoto.cn?c=a&c=b&c=c&c=d&c=k

reward:
  enable: true
  icon: ri:hand-coin-line
  comment: éƒ½çœ‹äº†è¿™ä¹ˆå¤šæ–‡ç« äº†ï¼Œä¸è€ƒè™‘æ‰“ç‚¹é’±å—ï¼ˆ
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: æ”¯ä»˜å®
      path: https://s2.loli.net/2022/06/12/uGYRtVW4378kKp1.png
      color: "#00A3EE"
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      path: https://s2.loli.net/2022/06/12/a6A5utXIlcVWCMv.png
      color: "#12B7F5"
      icon: ri:qq-line
  
bg_image:
  enable: true
  url: https://s2.loli.net/2022/06/12/LDEoubKysTdR7Bw.jpg # recomend image related to your mode
  dark: https://s2.loli.net/2022/06/12/i2Vd6T1QUtb9cfS.png

cursor:
  enable: true
  default: https://cdn.jsdelivr.net/gh/Big-Cake-jpg/Image_For_My_Blog@main/cursors/Netherite%20Sword.cur
  pointer: https://cdn.jsdelivr.net/gh/Big-Cake-jpg/Image_For_My_Blog@main/cursors/Netherite%20Pickaxe.cur
  text: https://cdn.jsdelivr.net/gh/Big-Cake-jpg/Image_For_My_Blog@main/cursors/Beamstick.cur

banner:
  enable: true
  title: å¤§è›‹ç³•çš„çƒ˜ç„™åŠ
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

pjax:
  enable: true
  src: /js/pjax.js

avatar:
  enable: true
  url: https://s2.loli.net/2022/06/12/RpGChkMjcwIOAaJ.jpg
  # If true, the avatar would be dispalyed in circle.
  rounded: true
  # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜¿
    message: æˆ‘ä¸æƒ³å»å­¦æ ¡ï¼ˆï¼ˆï¼ˆ

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue

social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  - name: QQ
    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
    link: http://wpa.qq.com/msgrd?v=3&uin=2577117205&site=qq&menu=yes
    icon: ri:qq-line
    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/Big-Cake-jpg
    icon: ri:github-line
    color: "#6e5494"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=3812611237
    icon: ri:netease-cloud-music-line
    color: "#C20C0C"
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/bigcake-19
    icon: ri:zhihu-line
    color: "#0084FF"
  - name: Twitter
    link: https://twitter.com/BigCake080105
    icon: ri:twitter-line
    color: "#1da1f2"
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/523235567
    icon: ri:bilibili-line
    color: "#FF8EB3"
  # - name: POPI
  #   link: https://www.popiapp.cn/elpsycn
  #   icon: ri:questionnaire-line
  #   color: "#525252"
  - name: E-Mail
    link: mailto:bigcake@cakemc.top
    icon: ri:mail-line
    color: "#8E71C1"
  - name: Telegram
    link: https://t.me/BigCakeBlog
    icon: ri:telegram-line
    color: "#0088CC"

favicon: https://s2.loli.net/2022/06/12/RpGChkMjcwIOAaJ.jpg

baidu_push: true

feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

mourn:
  enable: true
  days:
    - "4-4"
    - "9-18"
    - "12-13"

local_search:
  enable: false
  src: /js/search/local-search.js

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
  custom:
    title: ä¸‹ä¸€ç«™
    path: https://skin.cakemc.top
    icon: ri:arrow-right-line

google_analytics:
  enable: true
  # GA4
  id: G-WXBXYV2R6B

footer:
  since: 2021

  # Icon between year and copyright info.
  icon:
    # `heart` is recommended with animation in red (#ff0000).
    name: ri:cloud-line
    # If you want to animate the icon, set it to true.
    animated: true
    # Change the color of icon, using Hex Code.
    color: "#0078E7"
    # url: https://sponsors.yunyoujun.cn
    # title: äº‘æ¸¸å›çš„èµåŠ©è€…ä»¬
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2021-09-20T22:15:00"
  powered:
    # Hexo link (Powered by Hexo).
    enable: true
  support:
    enable: true
    title: åˆæ‹äº‘
    link: https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral
    logo: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/logo/upyun-logo.png
    prefix: æœ¬ç½‘ç«™ç”±
    suffix: æä¾› CDN åŠ é€Ÿä¸äº‘å­˜å‚¨æœåŠ¡

google_adsense:
  enable: true
  client: ca-pub-3406300839504314

comment:
  enable: true
  icon: ri:chat-3-line
  tips:
    - å¯ä»¥è¯´å‡ å¥è¯å˜›^_^å¦‚æœçœ‹ä¸åˆ°è¯„è®ºï¼Œè¯·åˆ·æ–°å‡ æ¬¡
  candidates:
    - waline
utterances:
  enable: false
  repo: Big-Cake-jpg/big-cake-jpg.github.io
  issue-term: title
  label: comment
  theme: github-light
waline:
  enable: true
  serverURL: https://waline.bigcake.cakemc.top
  comment: true
  emoji:
    - https://npm.elemecdn.com/@waline/emojis@latest/bilibili/
    - https://npm.elemecdn.com/@waline/emojis@latest/weibo/
    - https://npm.elemecdn.com/@waline/emojis@latest/qq/
  locale:
    placeholder: æ±‚æ±‚ä½ äº†ï¼Œå†™ç‚¹è¯„è®ºå§ï¼ˆè¯·å…ˆç™»å½•ï¼‰
    
leancloud_visitors:
  enable: true
  app_id: ErznielzJTc0MWHWtbaznYKO-MdYXbMMI
  app_key: iK4BuSm3M35dNsuMerVlq3JO

wordcount:
  enable: true
  count: true
  time: true
  
colors:
  primary: "#F2BC57"
  bg: "#F2F2F2"
  
fireworks:
  enable: true
  colors:
    - "115, 75, 52"
    - "242, 188, 87"
    - "242, 205, 94"
    - "242, 242, 242"

algolia_search:
  enable: true

vendors:
  host: https://npm.elemecdn.com/
  waline:
    js: https://npm.elemecdn.com/@waline/client@v2/dist/waline.js
    css: https://npm.elemecdn.com/@waline/client@v2/dist/waline.css
  aplayer:
    js: https://npm.elemecdn.com/aplayer/dist/APlayer.min.js
    css: https://npm.elemecdn.com/aplayer/dist/APlayer.min.css
    meting: https://npm.elemecdn.com/meting/dist/Meting.min.js

medium_zoom: true
